config/routes.rb
Rails.application.routes.draw do
  resources :books
  root 'books#index'

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_and_belongs_to_many :books
  
  validates :name, presence: true, uniqueness: true
end

app/models/book.rb
class Book < ActiveRecord::Base

  has_and_belongs_to_many :authors
  belongs_to :status
  
  before_save :default_values
  
  validates_presence_of :title, message: 'Nie podano tytułu'
  validates_uniqueness_of :title, message: 'Wybrana pozycja już istnieje'
  validates :cover_url, allow_blank: true, format: {
    with: %r{\.(gif|jpg|png)\Z}i,
    message: 'Zdjęcie okładki musi byc typu gif, jpg lub png.'
  }
  validates_associated :authors, :status
  
  def default_values
    self.status_id ||= 1
  end
  
  def self.search(search)
    if search
      where('title LIKE ?', "%#{search}%")
    end
  end
end

app/models/status.rb
class Status < ActiveRecord::Base
  has_many :books
  
  validates :name, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: [:show, :edit, :update, :destroy]
  helper_method :sort_column, :sort_direction
  
  # GET /books
  # GET /books.json
  def index
    if params[:search].nil? && params[:direction].nil?
      @books = Book.paginate(:per_page => 20, :page => params[:page])
    elsif params[:search].nil?
      @books = Book.order(params[:sort] + ' ' + params[:direction]).paginate(:per_page => 20, :page => params[:page])
    elsif params[:direction].nil?
      @books = Book.search(params[:search]).paginate(:per_page => 20, :page => params[:page])
    else
      @books = Book.search(params[:search]).order(params[:sort] + ' ' + params[:direction]).paginate(:per_page => 20, :page => params[:page])
   end
    
    #@statuses = Status.all
    @status_collection = Array.new
    Status.ids.each do |s|
      @status_collection << [s, Status.find(s).description]
    end
    
  end

  # GET /books/1
  # GET /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Book was successfully created.' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Book was successfully updated.' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Book was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :cover_url, :status_id)
    end
    
  def sort_column  
    Book.column_names.include?(params[:sort]) ? params[:sort] : 'name'  
  end  
    
  def sort_direction  
    %w{asc desc}.include?(params[:direction]) ?  params[:direction] : 'asc'  
  end
  

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
  def sortable(column, title)  
     if (column == sort_column && sort_direction == "asc")
       direction = "desc"
     else
      direction = "asc"
     end
    link_to title, params.merge(sort: column, direction: direction, page: nil)
  end  
end

app/views/books/_books.html.haml
= hidden_field_tag :direction, params[:direction]
= hidden_field_tag :sort, params[:sort]

app/views/books/_form.html.haml
= form_for @book do |f|
  - if @book.errors.any?
    #error_explanation
      %h2= "#{pluralize(@book.errors.count, "error")} prohibited this book from being saved:"
      // Wystąpił błąd podczas dodawania nowej pozycji do biblioteczki:
      %ul
        - @book.errors.messages.values.each do |msg|
          - msg.each do |m|
            %li= m
  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :cover_url
    = f.text_field :cover_url
  .field
    = f.collection_select(:status_id, Status.all, :id, :description)
  .actions
    = f.submit 'Save'

app/views/books/edit.html.haml
%h1 Editing book

= render 'form'

= link_to 'Show', @book
\|
= link_to 'Back', books_path

app/views/books/index.html.haml
%h1 Biblioteczka

= form_tag books_path, method: 'get' do
  = text_field_tag :search, params[:search], class: 'form-control'
  = submit_tag "Szukaj", name: nil, class: 'btn btn-default'
  = link_to books_path do
    = button_tag "Wyzeruj", class: 'btn btn-default'
  
%table.table.table-striped.table-hover
  %tr
    %th.col-md-2.col-sm-2.col-lg-2 Okładka
    %th.col-md-4.col-sm-4.col-lg-4= sortable 'title', 'Tytuł'
    %th.col-md-3.col-sm-3.col-lg-4 Autor
    %th.col-md-3.col-sm-3.col-lg-2= sortable 'status_id', 'Status'
    //%th 
    //%th
    //%th
  - @books.each do |book|
    %tr
      %td
        = link_to(image_tag(book.cover_url, class: 'cover', alt: 'Okładka książki "' + book.title + '"'), image_url(book.cover_url), {class: 'fancybox'})
      %td= book.title
      %td
        - book.authors.map(&:name).each do |author|
          - unless author == book.authors.map(&:name).last
            = author + ','
          - else
            = author
      %td= best_in_place book, :status_id, type: :select, collection: @status_collection
      
      //%td= link_to 'Show', book
      //%td= link_to 'Edit', edit_book_path(book)
      //%td= link_to 'Destroy', book, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br
= will_paginate @books
//= link_to 'New Book', new_book_path

app/views/books/index.js.haml
$("#books").html("= escape_javascript(render("books"))")

app/views/books/new.html.haml
%h1 New book

= render 'form'

= link_to 'Wróć', books_path

app/views/books/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @book.title
%p
  %b Cover url:
  = @book.cover_url

= link_to 'Edit', edit_book_path(@book)
\|
= link_to 'Back', books_path

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Biblioteczka
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    .container
      = yield